/**
 * Pharma Regulatory Intelligence — Curated Pipeline
 *
 * Static dataset of notable FDA and EMA regulatory decisions (2024–2026).
 * Decisions marked `isPending: true` have actionDate in the future.
 * Decisions marked `isPending: false` are historical with known outcomes.
 *
 * Data is supplemented at runtime by the openFDA API in /api/pharma/decisions.
 * Investment signals reflect market dynamics at the time of the decision or,
 * for pending items, the current pre-decision outlook.
 */

import type { RegulatoryDecision } from '@/types/pharma.types';

export const PHARMA_PIPELINE: RegulatoryDecision[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // DECIDED — APPROVED
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'kisunla-alz-fda-2024',
    brandName: 'Kisunla',
    genericName: 'donanemab',
    drugClass: 'Anti-amyloid monoclonal antibody',
    company: 'Eli Lilly',
    ticker: 'LLY',
    exchange: 'NYSE',
    indication: 'Early symptomatic Alzheimer\'s disease (amyloid-confirmed)',
    therapeuticArea: 'neurology',
    patientPopulation: '~6.7M eligible US patients',
    regulatoryBody: 'FDA',
    actionDate: '2024-07-02',
    isPending: false,
    status: 'approved',
    breakthroughTherapy: true,
    fastTrack: true,
    priorityReview: true,
    orphanDrug: false,
    adcom: {
      date: '2024-06-10',
      vote: '11-0 in favor',
      outcome: 'positive',
      committee: 'Peripheral and Central Nervous System Drugs Advisory Committee',
    },
    marketCapBillion: 730,
    stockReactionPercent: 2.7,
    peakSalesBillion: 5.0,
    investmentSignal: 'hold',
    signalRationale:
      'Approval was expected and largely priced in. Lecanemab (Leqembi) already on market creates competition. Strong LLY thesis driven by GLP-1 portfolio (Mounjaro/Zepbound) remains intact.',
    riskLevel: 'low',
    keyDrivers: ['First anti-amyloid with Tau-based stopping criterion', 'Differentiated dosing vs. Leqembi', 'LLY GLP-1 ecosystem upside'],
    riskFactors: ['ARIA (brain swelling) safety signal', 'Slow infusion-center ramp', 'Leqembi competition', 'CMS reimbursement uncertainty'],
    competitiveLandscape: 'Competes with Biogen/Eisai\'s Leqembi (lecanemab). Both are anti-amyloid mAbs; Kisunla may allow treatment cessation once amyloid cleared.',
    analystConsensus: 'Overweight — LLY trades at premium reflecting GLP-1 dominance; Kisunla adds optionality.',
  },

  {
    id: 'rezdiffra-mash-fda-2024',
    brandName: 'Rezdiffra',
    genericName: 'resmetirom',
    drugClass: 'Thyroid hormone receptor-β agonist',
    company: 'Madrigal Pharmaceuticals',
    ticker: 'MDGL',
    exchange: 'NASDAQ',
    indication: 'Non-cirrhotic NASH/MASH with moderate-to-advanced fibrosis (F2–F3)',
    therapeuticArea: 'metabolic',
    patientPopulation: '~17M MASH patients in the US',
    regulatoryBody: 'FDA',
    actionDate: '2024-03-14',
    isPending: false,
    status: 'approved',
    breakthroughTherapy: true,
    fastTrack: true,
    priorityReview: true,
    orphanDrug: false,
    marketCapBillion: 4.8,
    stockReactionPercent: 13.2,
    peakSalesBillion: 4.0,
    investmentSignal: 'buy',
    signalRationale:
      'First and only FDA-approved treatment for MASH — a 17M-patient market with no existing pharmacotherapy. Despite competition brewing (GLP-1s), Rezdiffra\'s mechanism and labeling differentiation provide a durable lead. Peak-sales upside remains significant for a ~$4B company.',
    riskLevel: 'medium',
    keyDrivers: ['First-mover in MASH', 'Orphan-like market dynamics early on', 'Expanded label potential to cirrhotic population'],
    riskFactors: ['GLP-1s (semaglutide, tirzepatide) showing MASH benefit in trials', 'Pricing pressure from PBMs', 'Slow physician education curve'],
    competitiveLandscape: 'Novo Nordisk and Lilly running Phase 3 MASH trials with GLP-1s. Rezdiffra\'s 24-month histology data provides near-term differentiation.',
  },

  {
    id: 'rytelo-mds-fda-2024',
    brandName: 'Rytelo',
    genericName: 'imetelstat',
    drugClass: 'Telomerase inhibitor (oligonucleotide)',
    company: 'Geron Corporation',
    ticker: 'GERN',
    exchange: 'NASDAQ',
    indication: 'Low-to-intermediate risk myelodysplastic syndrome (MDS), transfusion-dependent, relapsed/refractory to ESAs',
    therapeuticArea: 'hematology',
    regulatoryBody: 'FDA',
    actionDate: '2024-06-06',
    isPending: false,
    status: 'approved',
    breakthroughTherapy: false,
    fastTrack: true,
    priorityReview: true,
    orphanDrug: true,
    marketCapBillion: 1.2,
    stockReactionPercent: 28.4,
    peakSalesBillion: 0.8,
    investmentSignal: 'hold',
    signalRationale:
      'Post-approval, stock reflected the event. Revenue ramp is slow in a niche hematology market; commercial execution risk is high for a single-product company. Wait for early commercial data before adding.',
    riskLevel: 'high',
    keyDrivers: ['Only approved therapy in this line', 'Orphan drug pricing power', 'Potential label expansion to higher-risk MDS'],
    riskFactors: ['Small addressable market (~6,000 US patients/year in label)', 'Competitive luspatercept pressure', 'Single-product concentration risk'],
  },

  {
    id: 'winrevair-pah-fda-2024',
    brandName: 'Winrevair',
    genericName: 'sotatercept',
    drugClass: 'Activin receptor-ligand trap (ACVR2A-Fc fusion)',
    company: 'Merck & Co.',
    ticker: 'MRK',
    exchange: 'NYSE',
    indication: 'Pulmonary arterial hypertension (PAH) — adults',
    therapeuticArea: 'cardiology',
    patientPopulation: '~50,000 US PAH patients',
    regulatoryBody: 'FDA',
    actionDate: '2024-03-26',
    isPending: false,
    status: 'approved',
    breakthroughTherapy: true,
    fastTrack: true,
    priorityReview: false,
    orphanDrug: true,
    marketCapBillion: 260,
    stockReactionPercent: 5.1,
    peakSalesBillion: 3.5,
    investmentSignal: 'buy',
    signalRationale:
      'Novel first-in-class mechanism in PAH. STELLAR trial showed unprecedented improvements in exercise capacity and disease progression. PAH is a high-value market (~$10B). Adds to MRK\'s cardiovascular pipeline alongside Keytruda momentum.',
    riskLevel: 'low',
    keyDrivers: ['First-in-class activin receptor mechanism', 'Strong clinical differentiation (STELLAR 26% risk reduction)', 'Highly concentrated prescriber market — fast ramp potential'],
    riskFactors: ['Pricing negotiations', 'Johnson & Johnson competition with macitentan/tadalafil combo', 'Keytruda LOE in 2028 overhang on MRK overall'],
    competitiveLandscape: 'Existing PAH drugs (prostacyclins, ERAs, PDE5i) work by vasodilation; sotatercept reverses vascular remodeling — complementary rather than competitive.',
  },

  {
    id: 'imdelltra-sclc-fda-2024',
    brandName: 'Imdelltra',
    genericName: 'tarlatamab',
    drugClass: 'DLL3×CD3 bispecific T-cell engager (BiTE)',
    company: 'Amgen',
    ticker: 'AMGN',
    exchange: 'NASDAQ',
    indication: 'Extensive-stage small cell lung cancer (ES-SCLC), relapsed/refractory after platinum-based chemotherapy',
    therapeuticArea: 'oncology',
    regulatoryBody: 'FDA',
    actionDate: '2024-05-16',
    isPending: false,
    status: 'approved',
    breakthroughTherapy: true,
    fastTrack: false,
    priorityReview: true,
    orphanDrug: true,
    marketCapBillion: 160,
    stockReactionPercent: 3.8,
    peakSalesBillion: 2.0,
    investmentSignal: 'hold',
    signalRationale:
      'Meaningful advance in a historically difficult-to-treat cancer. However, SCLC market is relatively small and stock already priced in the approval. AMGN buyback program and Tezspire/obesity pipeline diversify the upside thesis.',
    riskLevel: 'medium',
    keyDrivers: ['First BiTE approved in SCLC', 'DLL3 is highly expressed in SCLC (>80% of tumors)', 'Potential expansion to first-line with atezolizumab combination'],
    riskFactors: ['Cytokine release syndrome safety management burden', 'SCLC market size ~25,000 US patients/year', 'Competitive BiTE pipeline from other manufacturers'],
  },

  {
    id: 'journavx-pain-fda-2025',
    brandName: 'Journavx',
    genericName: 'suzetrigine',
    drugClass: 'Selective Nav1.8 sodium channel blocker',
    company: 'Vertex Pharmaceuticals',
    ticker: 'VRTX',
    exchange: 'NASDAQ',
    indication: 'Moderate-to-severe acute pain in adults',
    therapeuticArea: 'other',
    regulatoryBody: 'FDA',
    actionDate: '2025-01-30',
    isPending: false,
    status: 'approved',
    breakthroughTherapy: true,
    fastTrack: true,
    priorityReview: true,
    orphanDrug: false,
    marketCapBillion: 55,
    stockReactionPercent: 8.5,
    peakSalesBillion: 2.5,
    investmentSignal: 'buy',
    signalRationale:
      'First new non-opioid, non-NSAID pain mechanism in decades. Nav1.8 selectivity avoids cardiac/CNS side effects of older sodium channel blockers. Chronic pain indication pending (larger market). VRTX\'s CF franchise generates stable cash while pain pipeline de-risks.',
    riskLevel: 'medium',
    keyDrivers: ['Non-opioid alternative (strong prescriber and payer tailwinds)', 'Potential $10B+ chronic pain market in future', 'FDA Breakthrough — demonstrated superiority vs. placebo and morphine in acute pain'],
    riskFactors: ['Opioid generics will always be cheaper', 'Formulary positioning uncertain', 'Chronic pain NDA still under review'],
    competitiveLandscape: 'No approved selective Nav1.8 blocker previously. Competes with opioids and NSAIDs on safety profile, not efficacy.',
  },

  {
    id: 'obicetrapib-crl-2024',
    brandName: 'N/A (CRL received)',
    genericName: 'obicetrapib',
    drugClass: 'CETP inhibitor',
    company: 'NewAmsterdam Pharma',
    ticker: 'NAMS',
    exchange: 'NASDAQ',
    indication: 'Atherosclerotic cardiovascular disease (ASCVD) — LDL-C lowering',
    therapeuticArea: 'cardiology',
    regulatoryBody: 'FDA',
    actionDate: '2024-09-19',
    isPending: false,
    status: 'crl',
    breakthroughTherapy: false,
    fastTrack: false,
    priorityReview: false,
    orphanDrug: false,
    marketCapBillion: 0.4,
    stockReactionPercent: -41.2,
    peakSalesBillion: 1.5,
    investmentSignal: 'watch',
    signalRationale:
      'CRL was unexpected — FDA cited manufacturing issues, not clinical data concerns. Clinical profile of obicetrapib remains strong (LDL reduction comparable to inclisiran). Company is addressing CMC deficiencies for resubmission. High risk/reward on resubmission timeline.',
    riskLevel: 'high',
    keyDrivers: ['CRL was manufacturing-related, not efficacy/safety', 'CETP mechanism raises HDL significantly (differentiated vs. statins/PCSK9i)', 'Resubmission possible within 12–18 months'],
    riskFactors: ['Regulatory uncertainty post-CRL', 'PCSK9 inhibitors (evolocumab, alirocumab) and inclisiran already entrenched', 'Small company — limited resources for lengthy resubmission process'],
    competitiveLandscape: 'PCSK9 inhibitors (Repatha, Praluent) and RNAi drug inclisiran dominate LDL-lowering beyond statins. Obicetrapib would compete on HDL mechanism differentiation.',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // DECIDED — EMA
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'mim8-hemophilia-ema-2025',
    brandName: 'Alhemo (EU)',
    genericName: 'concizumab',
    drugClass: 'Anti-TFPI monoclonal antibody',
    company: 'Novo Nordisk',
    ticker: 'NVO',
    exchange: 'NYSE',
    indication: 'Hemophilia A and B with inhibitors — prophylaxis',
    therapeuticArea: 'hematology',
    regulatoryBody: 'EMA',
    actionDate: '2025-03-17',
    isPending: false,
    status: 'approved',
    breakthroughTherapy: false,
    fastTrack: false,
    priorityReview: false,
    orphanDrug: true,
    marketCapBillion: 390,
    stockReactionPercent: 2.1,
    peakSalesBillion: 1.0,
    investmentSignal: 'hold',
    signalRationale:
      'Incremental approval for NVO in a niche population. NVO thesis primarily driven by obesity/diabetes pipeline. This approval adds modest upside but doesn\'t materially change the investment case.',
    riskLevel: 'low',
    keyDrivers: ['Rare disease orphan designation in EU', 'Subcutaneous once-weekly convenience vs. IV factor replacement'],
    riskFactors: ['Small patient population (hemophilia with inhibitors ~20% of hemophilia A)', 'Fitusiran (Alhemo, different drug) and emicizumab already established'],
    competitiveLandscape: 'Competes with Roche\'s emicizumab (Hemlibra) which has established strong market share in hemophilia A with inhibitors.',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PENDING — FDA (action dates after 2026-05-17)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'ivonescimab-nsclc-fda-2026',
    brandName: 'TBD',
    genericName: 'ivonescimab',
    drugClass: 'PD-1×VEGF bispecific antibody',
    company: 'Summit Therapeutics / Akeso',
    ticker: 'SMMT',
    exchange: 'NASDAQ',
    indication: 'PD-L1 positive non-small cell lung cancer (NSCLC) — first-line monotherapy',
    therapeuticArea: 'oncology',
    patientPopulation: '~130,000 US NSCLC patients/year (PD-L1 high)',
    regulatoryBody: 'FDA',
    actionDate: '2026-07-30',
    isPending: true,
    status: 'pending',
    breakthroughTherapy: false,
    fastTrack: true,
    priorityReview: true,
    orphanDrug: false,
    adcom: {
      date: '2026-06-25',
      vote: 'Pending',
      outcome: 'positive',
      committee: 'Oncologic Drugs Advisory Committee',
    },
    marketCapBillion: 4.2,
    peakSalesBillion: 8.0,
    investmentSignal: 'buy',
    signalRationale:
      'HARMONi-2 trial showed ivonescimab significantly outperformed pembrolizumab (Keytruda) in PD-L1 high NSCLC — a landmark result if confirmed by FDA review. If approved, disrupts a $25B+ Keytruda franchise. High binary event risk but asymmetric upside for SMMT (~$4B market cap vs. $8B peak sales estimate). Speculative position appropriate for high-risk-tolerant investors.',
    riskLevel: 'high',
    keyDrivers: [
      'Head-to-head win vs. Keytruda in pivotal trial (HARMONi-2)',
      'Dual PD-1 + VEGF blockade mechanism (additive over monotherapy)',
      'Priority Review granted — FDA sees substantial evidence of benefit',
      'Chinese trial data — FDA will scrutinize applicability to US population',
    ],
    riskFactors: [
      'Trial conducted in China — FDA may require additional US/global data',
      'Keytruda generics expected ~2028 (MRK label protection)',
      'SMMT lacks commercial infrastructure at scale',
      'Safety: VEGF axis concerns (hypertension, bleeding)',
    ],
    competitiveLandscape: 'Pembrolizumab (Keytruda, MRK) is the entrenched standard-of-care with $22B+ annual sales. Ivonescimab would directly threaten the largest oncology franchise globally.',
    analystConsensus: 'Highly contested — bulls see $10B+ peak sales; bears cite Chinese trial applicability concerns.',
  },

  {
    id: 'nivolumab-hcc-fda-2026',
    brandName: 'Opdivo + Yervoy',
    genericName: 'nivolumab + ipilimumab',
    drugClass: 'PD-1 + CTLA-4 checkpoint inhibitor combination',
    company: 'Bristol-Myers Squibb',
    ticker: 'BMY',
    exchange: 'NYSE',
    indication: 'Hepatocellular carcinoma (HCC) — first-line unresectable',
    therapeuticArea: 'oncology',
    patientPopulation: '~40,000 new HCC diagnoses/year in the US',
    regulatoryBody: 'FDA',
    actionDate: '2026-06-15',
    isPending: true,
    status: 'pending',
    breakthroughTherapy: false,
    fastTrack: false,
    priorityReview: false,
    orphanDrug: false,
    marketCapBillion: 140,
    peakSalesBillion: 1.8,
    investmentSignal: 'hold',
    signalRationale:
      'Approval likely but incrementally positive for BMY — HCC market has multiple competitors (atezolizumab+bevacizumab, tremelimumab+durvalumab). BMY\'s pipeline is improving but Opdivo LOE risk remains a concern. Approval expected to produce modest stock reaction.',
    riskLevel: 'low',
    keyDrivers: ['CheckMate-9DW data showed OS benefit vs. sorafenib', 'Combination is synergistic — CTLA-4+PD-1 more effective than mono', 'BMY rebuilding pipeline with Karuna/RayzeBio/SER acquisitions'],
    riskFactors: ['Atezolizumab+bevacizumab already dominant first-line', 'BMY LOE on several assets through 2028', 'HCC is a relatively small market'],
    competitiveLandscape: 'Roche\'s Tecentriq+Avastin remains standard-of-care. AZ\'s Imfinzi+tremelimumab (HIMALAYA) also approved. Crowded market.',
  },

  {
    id: 'iptacopan-ahus-fda-2026',
    brandName: 'Fabhalta (new indication)',
    genericName: 'iptacopan',
    drugClass: 'Complement factor B inhibitor',
    company: 'Novartis',
    ticker: 'NVS',
    exchange: 'NYSE',
    indication: 'Atypical hemolytic uremic syndrome (aHUS)',
    therapeuticArea: 'rare_disease',
    patientPopulation: '~5,000 US patients with aHUS',
    regulatoryBody: 'FDA',
    actionDate: '2026-06-28',
    isPending: true,
    status: 'pending',
    breakthroughTherapy: false,
    fastTrack: true,
    priorityReview: true,
    orphanDrug: true,
    marketCapBillion: 220,
    peakSalesBillion: 2.0,
    investmentSignal: 'hold',
    signalRationale:
      'Oral iptacopan vs. IV eculizumab/ravulizumab is a meaningful convenience advantage. NVS already approved for PNH — aHUS label extension incremental positive but not a thesis changer for a $220B company. NVS trades at attractive valuation with Kisqali/Cosentyx/Entresto.',
    riskLevel: 'low',
    keyDrivers: ['Oral administration vs. IV competitor (eculizumab — Soliris)', 'Proximal complement inhibition (factor B) — differentiated mechanism', 'Orphan drug pricing ($400K+/yr range possible)'],
    riskFactors: ['Alexion (AZ) has deeply entrenched eculizumab/ravulizumab relationships', 'Small patient population limits absolute commercial upside', 'NVS stock already reflects pipeline richness'],
    competitiveLandscape: 'AstraZeneca/Alexion dominant with eculizumab (Soliris) and ravulizumab (Ultomiris). Oral administration is a genuine differentiator.',
  },

  {
    id: 'zilebesiran-htn-fda-2026',
    brandName: 'TBD',
    genericName: 'zilebesiran',
    drugClass: 'RNAi therapeutic targeting angiotensinogen (AGT)',
    company: 'Alnylam Pharmaceuticals / Roche',
    ticker: 'ALNY',
    exchange: 'NASDAQ',
    indication: 'Uncontrolled hypertension — add-on to standard antihypertensives',
    therapeuticArea: 'cardiology',
    patientPopulation: '~116M US adults with hypertension; ~50M inadequately controlled',
    regulatoryBody: 'FDA',
    actionDate: '2026-08-12',
    isPending: true,
    status: 'pending',
    breakthroughTherapy: false,
    fastTrack: true,
    priorityReview: false,
    orphanDrug: false,
    marketCapBillion: 28,
    peakSalesBillion: 4.0,
    investmentSignal: 'strong_buy',
    signalRationale:
      'Zilebesiran could be transformative: a once-every-6-months subcutaneous injection that durably lowers blood pressure regardless of adherence. Phase 3 KARDIA-2 and KARDIA-1 data show consistent BP reduction (~15 mmHg systolic) on top of standard-of-care. 50M inadequately controlled hypertension patients in the US alone is a massive addressable market. ALNY at $28B market cap vs. $4B+ peak sales is compelling. Roche partnership validates commercial potential. Binary event risk warrants disciplined position sizing.',
    riskLevel: 'medium',
    keyDrivers: [
      'Once-every-6-months dosing — eliminates daily pill adherence problem',
      'Consistent BP reduction across all background therapies (KARDIA program)',
      'Roche partnership brings global commercial reach',
      'RNA interference mechanism is durable and precisely targeted',
      'Massive addressable market (~50M US hypertension patients)',
    ],
    riskFactors: [
      'Cardiorenal outcomes data not yet mature (surrogate endpoint approval)',
      'Large outcomes trial (KARDIA-4) data post-approval required',
      'Pricing/reimbursement hurdle vs. cheap generic antihypertensives',
      'Safety: long-acting mechanism means adverse events could persist',
    ],
    competitiveLandscape: 'Generic antihypertensives (ACE inhibitors, ARBs, amlodipine) dominate. Zilebesiran would carve out premium adherence-challenged segment. No direct RNAi competitor in hypertension.',
    analystConsensus: 'Bullish — most analysts see $3–5B peak sales. Some bearish on outcomes trial requirement.',
  },

  {
    id: 'tirzepatide-mash-fda-2026',
    brandName: 'Zepbound (MASH)',
    genericName: 'tirzepatide',
    drugClass: 'GIP/GLP-1 dual receptor agonist',
    company: 'Eli Lilly',
    ticker: 'LLY',
    exchange: 'NYSE',
    indication: 'Non-cirrhotic NASH/MASH with stage F2–F3 fibrosis (metabolic obesity-driven)',
    therapeuticArea: 'metabolic',
    patientPopulation: '~17M MASH patients in the US',
    regulatoryBody: 'FDA',
    actionDate: '2026-08-05',
    isPending: true,
    status: 'pending',
    breakthroughTherapy: true,
    fastTrack: true,
    priorityReview: false,
    orphanDrug: false,
    adcom: {
      date: '2026-06-30',
      vote: 'Pending',
      outcome: 'positive',
      committee: 'Gastrointestinal Drugs Advisory Committee',
    },
    marketCapBillion: 680,
    peakSalesBillion: 7.0,
    investmentSignal: 'buy',
    signalRationale:
      'SURMOUNT-NASH data showed tirzepatide resolves steatohepatitis and improves fibrosis — consistent with its obesity mechanism. If approved, tirzepatide would compete directly with Rezdiffra (resmetirom) in MASH with GLP-1/weight-loss additive benefits. LLY\'s label already covers sleep apnea and obesity; MASH is another large indication adding to a near-trillion-dollar franchise. Not a thesis changer for LLY but meaningful label expansion.',
    riskLevel: 'low',
    keyDrivers: [
      'GLP-1 mechanism treats root cause (metabolic obesity driving MASH)',
      'SURMOUNT-NASH: 63% MASH resolution without fibrosis worsening at 72 weeks',
      'Existing infrastructure — same drug as Zepbound for obesity',
      'Breakthrough Therapy designation',
    ],
    riskFactors: [
      'Resmetirom (Rezdiffra) already on market — physicians building habits',
      'GLP-1 class side effects (nausea, GI) in MASH patients',
      'LLY valuation leaves little room for disappointment',
    ],
    competitiveLandscape: 'Rezdiffra (Madrigal) is the incumbent. Semaglutide (Novo Nordisk) also running Phase 3 MASH trial. Multiple GLP-1s converging on this market.',
  },

  {
    id: 'cagrisema-obesity-fda-2026',
    brandName: 'CagriSema',
    genericName: 'cagrilintide + semaglutide 2.4mg',
    drugClass: 'Amylin analogue + GLP-1 receptor agonist combination',
    company: 'Novo Nordisk',
    ticker: 'NVO',
    exchange: 'NYSE',
    indication: 'Chronic weight management in adults with obesity (BMI ≥30) or overweight (BMI ≥27) with comorbidities',
    therapeuticArea: 'metabolic',
    patientPopulation: '~107M obese adults in the US',
    regulatoryBody: 'FDA',
    actionDate: '2026-09-25',
    isPending: true,
    status: 'pending',
    breakthroughTherapy: false,
    fastTrack: false,
    priorityReview: false,
    orphanDrug: false,
    marketCapBillion: 390,
    peakSalesBillion: 6.0,
    investmentSignal: 'buy',
    signalRationale:
      'REDEFINE-1 showed CagriSema produces ~22.7% body weight reduction — the highest of any weekly injectable currently. If approved, this would challenge tirzepatide\'s position as the leading obesity drug. NVO trades at a discount to LLY despite similar obesity franchise potential. Regulatory success could narrow the gap significantly.',
    riskLevel: 'medium',
    keyDrivers: [
      'Highest body weight reduction of any approved obesity drug (22.7% vs. Wegovy\'s ~15%)',
      'Combination synergy: amylin (satiety) + GLP-1 (appetite + glucose) dual mechanism',
      'NVO manufacturing scale for global commercial launch',
      'Semaglutide safety profile already well-characterized (embedded in combination)',
    ],
    riskFactors: [
      'REDEFINE trial had high discontinuation rate in some subgroups',
      'Tirzepatide (Mounjaro/Zepbound) entrenched with payers and prescribers',
      'Manufacturing ramp risk — two active ingredients to scale',
      'NVO needs to catch up commercially after Wegovy supply issues',
    ],
    competitiveLandscape: 'Direct competition with tirzepatide (Eli Lilly). Oral obesity drugs (Rybelsus high-dose, OIC) emerging. CagriSema would be strongest injectable for weight loss if approved.',
    analystConsensus: 'Mixed — bulls see $5–7B peak sales and NVO re-rating; bears note LLY\'s distribution network advantage.',
  },

  {
    id: 'pelacarsen-lpa-fda-2026',
    brandName: 'TBD',
    genericName: 'pelacarsen',
    drugClass: 'Antisense oligonucleotide targeting lipoprotein(a) [Lp(a)]',
    company: 'Novartis / Ionis Pharmaceuticals',
    ticker: 'NVS',
    exchange: 'NYSE',
    indication: 'Elevated Lp(a) with established cardiovascular disease — Lp(a) reduction to prevent MACE',
    therapeuticArea: 'cardiology',
    patientPopulation: '~64M US adults with elevated Lp(a) (≥50 mg/dL)',
    regulatoryBody: 'FDA',
    actionDate: '2026-11-20',
    isPending: true,
    status: 'pending',
    breakthroughTherapy: false,
    fastTrack: false,
    priorityReview: false,
    orphanDrug: false,
    marketCapBillion: 220,
    peakSalesBillion: 5.0,
    investmentSignal: 'strong_buy',
    signalRationale:
      'If HORIZON outcomes trial confirms cardiovascular risk reduction, pelacarsen would be the first approved Lp(a)-lowering therapy — addressing a massive genetic cardiovascular risk factor with no current treatment. 64M elevated Lp(a) patients, mostly not diagnosed. NVS/Ionis collaboration — IONS retains significant royalties (worth tracking separately). Positive HORIZON data is the single biggest near-term cardiovascular regulatory catalyst of 2026.',
    riskLevel: 'medium',
    keyDrivers: [
      'First-in-class: no approved Lp(a)-lowering therapy exists',
      'Lp(a) is a causal, genetic CV risk factor — large unmet need',
      'Phase 2 dose-finding showed ~80% Lp(a) reduction',
      'HORIZON Phase 3 outcome trial expected in H2 2026',
      'Muvalaplin (oral, Eli Lilly) competitor is still in Phase 2 — pelacarsen has timing advantage',
    ],
    riskFactors: [
      'HORIZON outcomes data not yet available — approval contingent on results',
      'Lp(a) awareness is low — physician education required at scale',
      'Subcutaneous monthly injection vs. future oral competitors',
      'Pricing/payer acceptance for broad CV indication',
    ],
    competitiveLandscape: 'Muvalaplin (LLY, oral) in Phase 2 — ~2 years behind. Olpasiran (Amgen) also in Phase 3 for Lp(a). Race to be first approved is key to capture prescriber loyalty.',
    analystConsensus: 'Broadly positive on Lp(a) class; debate on timing and which molecule wins.',
  },

  {
    id: 'ritlecitinib-atopy-fda-2026',
    brandName: 'Litfulo (new indication)',
    genericName: 'ritlecitinib',
    drugClass: 'JAK3/TEC kinase inhibitor',
    company: 'Pfizer',
    ticker: 'PFE',
    exchange: 'NYSE',
    indication: 'Moderate-to-severe atopic dermatitis (eczema) in adults and adolescents ≥12 years',
    therapeuticArea: 'immunology',
    patientPopulation: '~16.5M US adults with moderate-to-severe atopic dermatitis',
    regulatoryBody: 'FDA',
    actionDate: '2026-09-10',
    isPending: true,
    status: 'pending',
    breakthroughTherapy: false,
    fastTrack: false,
    priorityReview: false,
    orphanDrug: false,
    marketCapBillion: 145,
    peakSalesBillion: 2.5,
    investmentSignal: 'hold',
    signalRationale:
      'Ritlecitinib already approved for alopecia areata (Litfulo). Atopic dermatitis is a much larger market but highly competitive (dupilumab dominant, abrocitinib, baricitinib, upadacitinib). PFE faces an uphill commercial battle in a market where AbbVie\'s Rinvoq and Sanofi/Regeneron\'s Dupixent are entrenched. Approval likely but commercial differentiation unclear. PFE thesis hinges more on late-stage pipeline recovery and Paxlovid replacement.',
    riskLevel: 'low',
    keyDrivers: ['JAK3-selective mechanism has favorable cardiac safety profile vs. pan-JAK inhibitors', 'Oral pill vs. injectable dupilumab', 'Existing Litfulo infrastructure'],
    riskFactors: ['Dupixent has >$10B in AD revenues — very hard to displace', 'JAK class FDA black box warning (cardiovascular/malignancy) limits prescribing', 'PFE needs blockbuster to offset Paxlovid/Eliquis generic headwinds'],
    competitiveLandscape: 'Dupixent (Sanofi/REGN) dominates. Upadacitinib (AbbVie Rinvoq) #2. Ritlecitinib would enter as 4th-5th mover.',
  },

  {
    id: 'lanifibranor-mash-ema-2026',
    brandName: 'TBD',
    genericName: 'lanifibranor',
    drugClass: 'Pan-PPAR agonist (PPARα/δ/γ)',
    company: 'INVENTIVA / Nordic Bioscience',
    ticker: 'IVA',
    exchange: 'EPA',
    indication: 'Non-cirrhotic NASH/MASH with significant fibrosis (F2–F3)',
    therapeuticArea: 'metabolic',
    regulatoryBody: 'EMA',
    actionDate: '2026-07-18',
    isPending: true,
    status: 'pending',
    breakthroughTherapy: false,
    fastTrack: false,
    priorityReview: false,
    orphanDrug: false,
    marketCapBillion: 0.3,
    peakSalesBillion: 1.5,
    investmentSignal: 'watch',
    signalRationale:
      'INVENTIVA is a micro-cap European biotech with high binary event risk. Lanifibranor\'s NATIVE trial showed histological improvement in MASH — pending full Phase 3 confirmation. EMA approval would be a significant milestone for European MASH treatment (no currently approved therapy in EU). High risk/high reward for speculative investors only. GLP-1 headwinds in this market are significant.',
    riskLevel: 'high',
    keyDrivers: ['Pan-PPAR mechanism addresses inflammation, fibrosis, and metabolism simultaneously', 'First potential EMA-approved MASH drug', 'Phase 3 data showed statistically significant MASH resolution'],
    riskFactors: ['Very small company — commercial execution risk', 'GLP-1s entering MASH market from established companies', 'EU reimbursement negotiations complex'],
    competitiveLandscape: 'Rezdiffra (US approved). Multiple GLP-1s in European development. Lanifibranor would be first EU-approved if successful.',
  },
];

// Helper: sort by actionDate descending (most recent first)
export const SORTED_PIPELINE = [...PHARMA_PIPELINE].sort(
  (a, b) => b.actionDate.localeCompare(a.actionDate),
);

// Helper: upcoming decisions only
export const UPCOMING_PIPELINE = PHARMA_PIPELINE.filter(d => d.isPending).sort(
  (a, b) => a.actionDate.localeCompare(b.actionDate),
);

// Helper: decided (historical)
export const DECIDED_PIPELINE = PHARMA_PIPELINE.filter(d => !d.isPending).sort(
  (a, b) => b.actionDate.localeCompare(a.actionDate),
);
